### PR TITLE
SOCK5 support

### PR DESCRIPTION
**Pull request by Kokonico**
this allows the program to pull a list of SOCK5 proxies from a text file, and use them to push messages.

no file has been included, but it can now avoid being blocked via IP.

## New Dependencies

the project now requires pysocks.

### CODE REVIEW

**Comment by opticaldrive** [comment]
Nice!!!!

**Review by pxldevv — COMMENTED** [review]
Looks good, what happens if the proxies file doesn't exist though @Kokonico

**Review by taciturnaxolotl — APPROVED** [review]
lgtm!

**Comment by Kokonico** [comment]
@Techpro709 it'll crash :P, but I can add error handling if you want.

**Comment by pxldevv** [comment]
That would be great. It's alr merged though so don't worry about rushing it @Kokonico.

**Comment by opticaldrive** [comment]
Perhaps update the readme to mention the new dependency

**Comment by taciturnaxolotl** [comment]
added!

**Pull request merged**
